name: Good First Issue Welcome

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  welcome-new-contributor:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'good first issue'
    
    steps:
      - name: Post welcome comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `This issue is a great starting point for new contributors! 

Read here how to run the project: https://www.archestra.ai/docs/developer-quickstart
And here how to contribute: https://www.archestra.ai/docs/contributing

Good luck and welcome to the contributing team! Please don't hesitate to ask questions if you need any help right here in the comments.`
            });